steps:    
  - label: "Repo Man"
    plugins:
        ssh://git@github.com/alianza-dev/repo-man-buildkite-plugin.git#v0.0.12:
          accounts_allowed_access: 
           - 887225055373
           - 168166776662
          iam_role_arn: arn:aws:iam::887225055373:role/cloudmeetings_lab
          repo: cm-meetings
          repo_region: us-east-2
  
  - label: ":hammer: Build"
    plugins:
        ecr#v1.1.4:
          login: true
          account_ids: 887225055373
          no-include-email: true
          region: us-east-2
        ssh://git@github.com/alianza-dev/smart-maven-buildkite-plugin.git#v4.3.1:
          job: build
          java_major_version: 11
          publish_shapshots: enabled
